# Generated by Django 5.2.7 on 2025-11-09 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encryptedmessenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-created_at']},
        ),
    ]
