# Generated by Django 5.2.8 on 2025-11-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("encryptedmessenger", "0002_alter_conversation_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="autodestruct_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
